resolver: lts-8.17
packages:
packages:
- location: '.'
- location: 
    git: https://github.com/byteally/dbrecord.git
    commit: fb85ae90408750790336d154a2cb715a2425e085

extra-deps: []

extra-package-dbs: []
